/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Bytes {
  static new(): Bytes
  static fromBytes(data: Uint8Array): Bytes
  static fromString(value: string): Bytes
  get isEmpty(): boolean
  get len(): number
  toBytes(): Uint8Array
  toString(): string
}

export declare class CancellationToken {
  constructor()
  cancel(): Promise<void>
  /** Returns true if the token was cancelled (i.e. `cancel` was called). */
  get isCancelled(): boolean
}

export declare class Config {
  static default(): Config
  static defaultConfigPathEnv(): string
  static fromEnv(): Config
  static fromFile(path: string): Config
  static fromJson5(input: string): Config
  getJson(key: string): string
  insertJson5(key: string, value: string): void
  remove(key: string): void
}

export declare class Encoding {
  static default(): Encoding
  static from(value: string): Encoding
  static zenohBytes(): Encoding
  static zenohString(): Encoding
  static zenohSerialized(): Encoding
  static applicationOctetStream(): Encoding
  static textPlain(): Encoding
  static applicationJson(): Encoding
  static textJson(): Encoding
  static applicationCdr(): Encoding
  static applicationCbor(): Encoding
  static applicationYaml(): Encoding
  static textYaml(): Encoding
  static textJson5(): Encoding
  static applicationPythonSerializedObject(): Encoding
  static applicationProtobuf(): Encoding
  static applicationJavaSerializedObject(): Encoding
  static applicationOpenmetricsText(): Encoding
  static imagePng(): Encoding
  static imageJpeg(): Encoding
  static imageGif(): Encoding
  static imageBmp(): Encoding
  static imageWebp(): Encoding
  static applicationXml(): Encoding
  static applicationXWwwFormUrlencoded(): Encoding
  static textHtml(): Encoding
  static textXml(): Encoding
  static textCss(): Encoding
  static textJavascript(): Encoding
  static textMarkdown(): Encoding
  static textCsv(): Encoding
  static applicationSql(): Encoding
  static applicationCoapPayload(): Encoding
  static applicationJsonPatchJson(): Encoding
  static applicationJsonSeq(): Encoding
  static applicationJsonpath(): Encoding
  static applicationJwt(): Encoding
  static applicationMp4(): Encoding
  static applicationSoapXml(): Encoding
  static applicationYang(): Encoding
  static audioAac(): Encoding
  static audioFlac(): Encoding
  static audioMp4(): Encoding
  static audioOgg(): Encoding
  static audioVorbis(): Encoding
  static videoH261(): Encoding
  static videoH263(): Encoding
  static videoH264(): Encoding
  static videoH265(): Encoding
  static videoH266(): Encoding
  static videoMp4(): Encoding
  static videoOgg(): Encoding
  static videoRaw(): Encoding
  static videoVp8(): Encoding
  static videoVp9(): Encoding
  toString(): string
  withSchema(value: string): Encoding
}

export declare class EndPoint {
  constructor(protocol: string, address: string, metadata: string, config: string)
  get protocol(): string
  get address(): string
  toString(): string
  metadata(): Metadata
  config(): string
  split(): EndPointParts
  toLocator(): Locator
}

export declare class EntityGlobalId {
  get zid(): string
  get eid(): number
}

export declare class FifoChannel {
  constructor(capacity: number)
  static default(): FifoChannel
}

export declare class Hello {
  locators(): Array<Locator>
  get whatami(): WhatAmI
  get zid(): string
}

export declare class KeyExpr {
  constructor(expr: string)
  static autocanonize(expr: string): KeyExpr
  static fromStr(expr: string): KeyExpr
  concat(other: string): KeyExpr
  join(other: string): KeyExpr
  toString(): string
  intersects(other: KeyExpr): boolean
  includes(other: KeyExpr): boolean
  get isWild(): boolean
}

export declare class Link {
  get zid(): string
  get src(): Locator
  get dst(): Locator
  get group(): Locator | null
  get mtu(): number
  get isStreamed(): boolean
  get interfaces(): Array<string>
  get authIdentifier(): string | null
  get priorities(): LinkPriorities | null
  get reliability(): Reliability | null
}

export declare class Liveliness {
  declareToken(keyExpr: KeyExprArg): Promise<LivelinessToken>
  declareSubscriber(keyExpr: KeyExprArg, options?: LivelinessSubscriberOptions | undefined | null): Promise<LivelinessSubscriber>
  get(keyExpr: KeyExprArg, options?: LivelinessGetOptions | undefined | null): Promise<Replies>
}

export declare class LivelinessSubscriber {
  get keyExpr(): KeyExpr
  get id(): EntityGlobalId
  recv(): Promise<Sample>
  tryRecv(): Sample | null
  drain(): Array<Sample>
  isDisconnected(): boolean
  isEmpty(): boolean
  isFull(): boolean
  len(): number
  capacity(): number | null
  senderCount(): number
  receiverCount(): number
  stream(): ReadableStream<Sample>
  undeclare(): Promise<undefined>
}

export declare class LivelinessToken {
  undeclare(): Promise<undefined>
}

export declare class Locator {
  constructor(protocol: string, address: string, metadata: string)
  get protocol(): string
  get address(): string
  toString(): string
  metadata(): Metadata
  toEndpoint(): EndPoint
}

export declare class MatchingListener {
  recv(): Promise<MatchingStatus>
  tryRecv(): MatchingStatus | null
  drain(): Array<MatchingStatus>
  isDisconnected(): boolean
  isEmpty(): boolean
  isFull(): boolean
  len(): number
  capacity(): number | null
  senderCount(): number
  receiverCount(): number
  stream(): ReadableStream<MatchingStatus>
  undeclare(): Promise<undefined>
}

export declare class MatchingStatus {
  get matching(): boolean
}

export declare class Metadata {
  toString(): string
  isEmpty(): boolean
  get(key: string): string | null
  values(key: string): Array<string>
}

export declare class Miss {
  get source(): EntityGlobalId
  get nb(): number
}

export declare class Parameters {
  static empty(): Parameters
  constructor(params: string)
  toString(): string
  get isEmpty(): boolean
  get isOrdered(): boolean
  containsKey(key: string): boolean
  get(key: string): string | null
  values(key: string): Array<string>
  insert(key: string, value: string): string | null
  remove(key: string): string | null
  extend(other: Parameters): void
}

export declare class Publisher {
  get keyExpr(): KeyExpr
  get id(): EntityGlobalId
  get encoding(): Encoding
  get congestionControl(): CongestionControl
  get priority(): Priority
  put(payload: PayloadArg, options?: PublisherPutOptions | undefined | null): Promise<undefined>
  delete(options?: PublisherDeleteOptions | undefined | null): Promise<undefined>
  matchingStatus(): Promise<MatchingStatus>
  matchingListener(options?: MatchingListenerOptions | undefined | null): Promise<MatchingListener>
  undeclare(): Promise<undefined>
}

export declare class Querier {
  get keyExpr(): KeyExpr
  get id(): EntityGlobalId
  get congestionControl(): CongestionControl
  get priority(): Priority
  get acceptReplies(): ReplyKeyExpr
  get(options?: QuerierGetOptions | undefined | null): Promise<Replies>
  matchingStatus(): Promise<MatchingStatus>
  matchingListener(options?: MatchingListenerOptions | undefined | null): Promise<MatchingListener>
  undeclare(): Promise<undefined>
}

export declare class Query {
  get selector(): Selector
  get keyExpr(): KeyExpr
  get payload(): Bytes | null
  get encoding(): Encoding | null
  get attachment(): Bytes | null
  get sourceInfo(): SourceInfo | null
  get priority(): Priority
  get congestionControl(): CongestionControl
  get express(): boolean
  get parameters(): Parameters
  get acceptReplies(): ReplyKeyExpr
  reply(keyExpr: KeyExprArg, payload: PayloadArg, options?: ReplyOptions | undefined | null): Promise<undefined>
  replyErr(payload: PayloadArg, options?: ReplyErrOptions | undefined | null): Promise<void>
  replyDel(keyExpr: KeyExprArg, options?: ReplyDelOptions | undefined | null): Promise<undefined>
}

export declare class Queryable {
  get id(): EntityGlobalId
  get keyExpr(): KeyExpr
  recv(): Promise<Query>
  tryRecv(): Query | null
  drain(): Array<Query>
  isDisconnected(): boolean
  isEmpty(): boolean
  isFull(): boolean
  len(): number
  capacity(): number | null
  senderCount(): number
  receiverCount(): number
  stream(): ReadableStream<Query>
  undeclare(): Promise<undefined>
}

export declare class Replies {
  recv(): Promise<Reply>
  tryRecv(): Reply | null
  drain(): Array<Reply>
  isDisconnected(): boolean
  isEmpty(): boolean
  isFull(): boolean
  len(): number
  capacity(): number | null
  senderCount(): number
  receiverCount(): number
  stream(): ReadableStream<Reply>
}

export declare class Reply {
  result(): Sample | ReplyError
  get replierId(): EntityGlobalId | null
}

export declare class ReplyError {
  get encoding(): Encoding
  get payload(): Bytes
}

export declare class RingChannel {
  constructor(capacity: number)
  static default(): RingChannel
}

export declare class Sample {
  get payload(): Bytes
  get keyExpr(): KeyExpr
  get kind(): SampleKind
  get encoding(): Encoding
  get timestamp(): Timestamp | null
  get express(): boolean
  get priority(): Priority
  get congestionControl(): CongestionControl
  get reliability(): Reliability
  get attachment(): Bytes | null
  get sourceInfo(): SourceInfo | null
}

export declare class SampleMissListener {
  recv(): Promise<Miss>
  tryRecv(): Miss | null
  drain(): Array<Miss>
  isDisconnected(): boolean
  isEmpty(): boolean
  isFull(): boolean
  len(): number
  capacity(): number | null
  senderCount(): number
  receiverCount(): number
  stream(): ReadableStream<Miss>
  undeclare(): Promise<undefined>
}

export declare class Scout {
  static scout(what: WhatAmIMatcher, config: Config, options?: ScoutOptions | undefined | null): Promise<Scout>
  recv(): Promise<Hello>
  tryRecv(): Hello | null
  drain(): Array<Hello>
  isDisconnected(): boolean
  isEmpty(): boolean
  isFull(): boolean
  len(): number
  capacity(): number | null
  senderCount(): number
  receiverCount(): number
  stream(): ReadableStream<Hello>
  stop(): void
}

export declare class Selector {
  constructor(keyExpr: KeyExprArg, parameters?: string | undefined | null)
  get keyExpr(): KeyExpr
  get parameters(): Parameters
  split(): SelectorParts
}

export declare class Session {
  static open(config: Config): Promise<Session>
  get zid(): string
  get id(): EntityGlobalId
  get isClosed(): boolean
  newTimestamp(): Timestamp
  info(): SessionInfo
  config(): SessionConfig
  close(): Promise<void>
  put(keyExpr: KeyExprArg, payload: PayloadArg, options?: PutOptions | undefined | null): Promise<undefined>
  get(selector: SelectorArg, options?: GetOptions | undefined | null): Promise<Replies>
  delete(keyExpr: KeyExprArg, options?: DeleteOptions | undefined | null): Promise<undefined>
  liveliness(): Liveliness
  declareKeyexpr(keyExpr: KeyExprArg): Promise<KeyExpr>
  declareQuerier(keyExpr: KeyExprArg, options?: QuerierOptions | undefined | null): Promise<Querier>
  declareQueryable(keyExpr: KeyExprArg, options?: QueryableOptions | undefined | null): Promise<Queryable>
  declareSubscriber(keyExpr: KeyExprArg, options?: SubscriberOptions | undefined | null): Promise<Subscriber>
  declarePublisher(keyExpr: KeyExprArg, options?: PublisherOptions | undefined | null): Promise<Publisher>
}

export declare class SessionConfig {
  get(key: string): string
  insertJson5(key: string, value: string): void
  toJson(): string
  queriesDefaultTimeoutMs(): bigint
  getPluginConfig(pluginName: string): string
}

export declare class SessionInfo {
  zid(): Promise<string>
  routersZid(): Promise<Array<string>>
  peersZid(): Promise<Array<string>>
  transports(): Promise<Array<Transport>>
  links(): Promise<Array<Link>>
}

export declare class SourceInfo {
  constructor(sourceId: EntityGlobalId, sourceSn: number)
  get sourceId(): EntityGlobalId
  get sourceSn(): number
}

export declare class Subscriber {
  get keyExpr(): KeyExpr
  get id(): EntityGlobalId
  recv(): Promise<Sample>
  tryRecv(): Sample | null
  drain(): Array<Sample>
  stream(): ReadableStream<Sample>
  isEmpty(): boolean
  isFull(): boolean
  isDisconnected(): boolean
  len(): number
  capacity(): number | null
  senderCount(): number
  receiverCount(): number
  sampleMissListener(options?: SampleMissListenerOptions | undefined | null): Promise<SampleMissListener>
  detectPublishers(options?: LivelinessSubscriberOptions | undefined | null): Promise<LivelinessSubscriber>
  undeclare(): Promise<undefined>
}

export declare class Timestamp {
  static parseRfc3339(s: string): Timestamp
  toStringRfc3339Lossy(): string
  getTime(): bigint
  getId(): string
  getDiffDuration(other: Timestamp): number
}

export declare class Transport {
  get zid(): string
  get whatami(): WhatAmI
  get isQos(): boolean
  get isMulticast(): boolean
}

export declare class WhatAmIMatcher {
  static empty(): WhatAmIMatcher
  router(): WhatAmIMatcher
  peer(): WhatAmIMatcher
  client(): WhatAmIMatcher
  get isEmpty(): boolean
  matches(w: WhatAmI): boolean
  toStr(): string
}

export interface CacheConfig {
  maxSamples?: number
  repliesConfig?: RepliesConfig
}

export type ChannelArg =
  FifoChannel | RingChannel

export type CongestionControl =  'Drop'|
'Block'|
'BlockFirst';

export type ConsolidationMode =  'Auto'|
'None'|
'Monotonic'|
'Latest';

export interface DeleteOptions {
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  reliability?: Reliability
  allowedDestination?: Locality
  timestamp?: Timestamp
  attachment?: Uint8Array
  sourceInfo?: SourceInfo
}

export interface EndPointParts {
  protocol: string
  address: string
  metadata: string
  config: string
}

export interface GetOptions {
  parameters?: Parameters
  target?: QueryTarget
  consolidation?: ConsolidationMode
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  allowedDestination?: Locality
  timeout?: number
  payload?: Uint8Array
  encoding?: string
  attachment?: Uint8Array
  sourceInfo?: SourceInfo
  cancellationToken?: CancellationToken
  capacity?: number
}

export interface HeartbeatConfig {
  periodMs: number
  sporadic?: boolean
}

export type HeartbeatMode =  'Heartbeat';

export interface HeartbeatRecovery {
  mode: HeartbeatMode
}

export interface HistoryConfig {
  detectLatePublishers?: boolean
  maxSamples?: number
  maxAgeSecs?: number
}

export type KeyExprArg =
  string | KeyExpr

export interface LinkPriorities {
  min: number
  max: number
}

export interface LivelinessGetOptions {
  timeout?: number
  cancellationToken?: CancellationToken
  capacity?: number
}

export interface LivelinessSubscriberOptions {
  history?: boolean
  capacity?: number
}

export type Locality =  'SessionLocal'|
'Remote'|
'Any';

export interface MatchingListenerOptions {
  capacity?: number
}

export interface MissDetectionConfig {
  heartbeat?: HeartbeatConfig
}

export type PayloadArg =
  string | Uint8Array

export type PeriodicQueriesMode =  'PeriodicQueries';

export interface PeriodicQueriesRecovery {
  mode: PeriodicQueriesMode
  periodMs: number
}

export type Priority =  'RealTime'|
'InteractiveHigh'|
'InteractiveLow'|
'DataHigh'|
'Data'|
'DataLow'|
'Background';

export interface PublisherDeleteOptions {
  timestamp?: Timestamp
  attachment?: Uint8Array
}

export interface PublisherOptions {
  encoding?: string
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  reliability?: Reliability
  allowedDestination?: Locality
  cache?: CacheConfig
  sampleMissDetection?: MissDetectionConfig
  publisherDetection?: boolean
  publisherDetectionMetadata?: string
}

export interface PublisherPutOptions {
  encoding?: string
  timestamp?: Timestamp
  attachment?: Uint8Array
}

export interface PutOptions {
  encoding?: string
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  reliability?: Reliability
  allowedDestination?: Locality
  timestamp?: Timestamp
  attachment?: Uint8Array
  sourceInfo?: SourceInfo
}

export interface QuerierGetOptions {
  parameters?: Parameters
  payload?: Uint8Array
  encoding?: string
  attachment?: Uint8Array
  sourceInfo?: SourceInfo
  cancellationToken?: CancellationToken
  capacity?: number
}

export interface QuerierOptions {
  target?: QueryTarget
  consolidation?: ConsolidationMode
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  allowedDestination?: Locality
  timeout?: number
  acceptReplies?: ReplyKeyExpr
}

export interface QueryableOptions {
  complete?: boolean
  allowedOrigin?: Locality
  capacity?: number
}

export type QueryTarget =  'BestMatching'|
'All'|
'AllComplete';

export type Reliability =  'BestEffort'|
'Reliable';

export interface RepliesConfig {
  priority?: Priority
  congestionControl?: CongestionControl
  express?: boolean
}

export interface ReplyDelOptions {
  express?: boolean
  timestamp?: Timestamp
  attachment?: Uint8Array
  sourceInfo?: SourceInfo
}

export interface ReplyErrOptions {
  encoding?: string
}

export type ReplyKeyExpr =  'Any'|
'MatchingQuery';

export interface ReplyOptions {
  encoding?: string
  express?: boolean
  timestamp?: Timestamp
  attachment?: Uint8Array
  sourceInfo?: SourceInfo
}

export type SampleKind =  'Put'|
'Delete';

export interface SampleMissListenerOptions {
  capacity?: number
}

export interface ScoutOptions {
  capacity?: number
}

export type SelectorArg =
  string | KeyExpr | Selector

export interface SelectorParts {
  keyExpr: string
  parameters: string
}

export interface SubscriberOptions {
  allowedOrigin?: Locality
  history?: HistoryConfig
  recovery?: PeriodicQueriesRecovery | HeartbeatRecovery
  subscriberDetection?: boolean
  subscriberDetectionMetadata?: string
  queryTimeoutMs?: number
  capacity?: number
}

export type WhatAmI =  'Router'|
'Peer'|
'Client';
