/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Bytes {
  static new(): Bytes
  static fromBytes(data: Uint8Array): Bytes
  static fromString(value: string): Bytes
  get isEmpty(): boolean
  get len(): number
  toBytes(): Uint8Array
  /**
   * Decodes the payload as a UTF-8 string.
   *
   * @throws If the payload contains non-UTF-8 bytes. Zenoh does not guarantee
   * UTF-8, so this can fail; use {@link Bytes.toBytes} for arbitrary bytes.
   */
  tryToString(): string
}

export declare class CancellationToken {
  constructor()
  cancel(): Promise<void>
  /** Returns true if the token was cancelled (i.e. `cancel` was called). */
  get isCancelled(): boolean
}

export declare class Config {
  static default(): Config
  static defaultConfigPathEnv(): string
  static fromEnv(): Config
  static fromFile(path: string): Config
  static fromJson5(input: string): Config
  getJson(key: string): string
  insertJson5(key: string, value: string): void
  remove(key: string): void
}

export declare class Encoding {
  static default(): Encoding
  static from(value: string): Encoding
  static zenohBytes(): Encoding
  static zenohString(): Encoding
  static zenohSerialized(): Encoding
  static applicationOctetStream(): Encoding
  static textPlain(): Encoding
  static applicationJson(): Encoding
  static textJson(): Encoding
  static applicationCdr(): Encoding
  static applicationCbor(): Encoding
  static applicationYaml(): Encoding
  static textYaml(): Encoding
  static textJson5(): Encoding
  static applicationPythonSerializedObject(): Encoding
  static applicationProtobuf(): Encoding
  static applicationJavaSerializedObject(): Encoding
  static applicationOpenmetricsText(): Encoding
  static imagePng(): Encoding
  static imageJpeg(): Encoding
  static imageGif(): Encoding
  static imageBmp(): Encoding
  static imageWebp(): Encoding
  static applicationXml(): Encoding
  static applicationXWwwFormUrlencoded(): Encoding
  static textHtml(): Encoding
  static textXml(): Encoding
  static textCss(): Encoding
  static textJavascript(): Encoding
  static textMarkdown(): Encoding
  static textCsv(): Encoding
  static applicationSql(): Encoding
  static applicationCoapPayload(): Encoding
  static applicationJsonPatchJson(): Encoding
  static applicationJsonSeq(): Encoding
  static applicationJsonpath(): Encoding
  static applicationJwt(): Encoding
  static applicationMp4(): Encoding
  static applicationSoapXml(): Encoding
  static applicationYang(): Encoding
  static audioAac(): Encoding
  static audioFlac(): Encoding
  static audioMp4(): Encoding
  static audioOgg(): Encoding
  static audioVorbis(): Encoding
  static videoH261(): Encoding
  static videoH263(): Encoding
  static videoH264(): Encoding
  static videoH265(): Encoding
  static videoH266(): Encoding
  static videoMp4(): Encoding
  static videoOgg(): Encoding
  static videoRaw(): Encoding
  static videoVp8(): Encoding
  static videoVp9(): Encoding
  toString(): string
  withSchema(value: string): Encoding
}

export declare class EndPoint {
  constructor(protocol: string, address: string, metadata: string, config: string)
  get protocol(): string
  get address(): string
  toString(): string
  metadata(): Metadata
  config(): string
  split(): EndPointParts
  toLocator(): Locator
}

export declare class EntityGlobalId {
  get zid(): string
  get eid(): number
}

export declare class FifoChannel {
  constructor(capacity: number)
}

export declare class Hello {
  locators(): Array<Locator>
  get whatami(): WhatAmI
  get zid(): string
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class HelloStream {
  [Symbol.asyncIterator](): AsyncGenerator<Hello, void, undefined>
}

export declare class KeyExpr {
  constructor(expr: string)
  static autocanonize(expr: string): KeyExpr
  static fromStr(expr: string): KeyExpr
  concat(other: string): KeyExpr
  join(other: string): KeyExpr
  toString(): string
  intersects(other: KeyExpr): boolean
  includes(other: KeyExpr): boolean
  get isWild(): boolean
}

export declare class Link {
  get zid(): string
  get src(): Locator
  get dst(): Locator
  get group(): Locator | null
  get mtu(): number
  get isStreamed(): boolean
  get interfaces(): Array<string>
  get authIdentifier(): string | null
  get priorities(): LinkPriorities | null
  get reliability(): Reliability | null
}

export declare class LinkEvent {
  get kind(): SampleKind
  get link(): Link
}

export declare class LinkEventsListener {
  undeclare(): void
  recv(): Promise<LinkEvent>
  tryRecv(): LinkEvent | null
  stream(): LinkEventStream
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class LinkEventStream {
  [Symbol.asyncIterator](): AsyncGenerator<LinkEvent, void, undefined>
}

export declare class Liveliness {
  declareToken(keyExpr: KeyExprArg): Promise<LivelinessToken>
  declareSubscriber(keyExpr: KeyExprArg, options?: LivelinessSubscriberOptions | undefined | null): Promise<LivelinessSubscriber>
  get(keyExpr: KeyExprArg, options?: LivelinessGetOptions | undefined | null): Promise<ReplyHandler>
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class LivelinessSampleStream {
  [Symbol.asyncIterator](): AsyncGenerator<Sample, void, undefined>
}

export declare class LivelinessSubscriber {
  get keyExpr(): KeyExpr
  get id(): EntityGlobalId
  undeclare(): void
  recv(): Promise<Sample>
  tryRecv(): Sample | null
  stream(): LivelinessSampleStream
}

export declare class LivelinessToken {
  undeclare(): void
}

export declare class Locator {
  constructor(protocol: string, address: string, metadata: string)
  get protocol(): string
  get address(): string
  toString(): string
  metadata(): Metadata
  toEndpoint(): EndPoint
}

export declare class MatchingListener {
  undeclare(): void
  recv(): Promise<MatchingStatus>
  tryRecv(): MatchingStatus | null
  stream(): MatchingStatusStream
}

export declare class MatchingStatus {
  get matching(): boolean
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class MatchingStatusStream {
  [Symbol.asyncIterator](): AsyncGenerator<MatchingStatus, void, undefined>
}

export declare class Metadata {
  toString(): string
  isEmpty(): boolean
  get(key: string): string | null
  values(key: string): Array<string>
}

export declare class Miss {
  get source(): EntityGlobalId
  get nb(): number
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class MissStream {
  [Symbol.asyncIterator](): AsyncGenerator<Miss, void, undefined>
}

export declare class Parameters {
  static empty(): Parameters
  constructor(params: string)
  toString(): string
  get isEmpty(): boolean
  get isOrdered(): boolean
  containsKey(key: string): boolean
  get(key: string): string | null
  values(key: string): Array<string>
  insert(key: string, value: string): string | null
  remove(key: string): string | null
  extend(other: Parameters): void
}

export declare class Publisher {
  get keyExpr(): KeyExpr
  get id(): EntityGlobalId
  get encoding(): Encoding
  get congestionControl(): CongestionControl
  get priority(): Priority
  put(payload: Payload, options?: PublisherPutOptions | undefined | null): Promise<void>
  delete(options?: PublisherDeleteOptions | undefined | null): Promise<void>
  matchingStatus(): Promise<MatchingStatus>
  matchingListener(options?: MatchingListenerOptions | undefined | null): Promise<MatchingListener>
  undeclare(): void
}

export declare class Querier {
  get keyExpr(): KeyExpr
  get id(): EntityGlobalId
  get congestionControl(): CongestionControl
  get priority(): Priority
  get acceptReplies(): ReplyKeyExpr
  get(options?: QuerierGetOptions | undefined | null): Promise<ReplyHandler>
  matchingStatus(): Promise<MatchingStatus>
  matchingListener(options?: MatchingListenerOptions | undefined | null): Promise<MatchingListener>
  undeclare(): void
}

export declare class Query {
  get selector(): Selector
  get keyExpr(): KeyExpr
  get payload(): Bytes | null
  get encoding(): Encoding | null
  get attachment(): Bytes | null
  get sourceInfo(): SourceInfo | null
  get priority(): Priority
  get congestionControl(): CongestionControl
  get express(): boolean
  get parameters(): Parameters
  get acceptsReplies(): ReplyKeyExpr
  reply(keyExpr: KeyExprArg, payload: Payload, options?: ReplyOptions | undefined | null): Promise<void>
  replyErr(payload: Payload, options?: ReplyErrOptions | undefined | null): Promise<void>
  replyDel(keyExpr: KeyExprArg, options?: ReplyDelOptions | undefined | null): Promise<void>
  drop(): void
}

export declare class Queryable {
  get id(): EntityGlobalId
  get keyExpr(): KeyExpr
  undeclare(): void
  recv(): Promise<Query>
  tryRecv(): Query | null
  stream(): QueryStream
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class QueryStream {
  [Symbol.asyncIterator](): AsyncGenerator<Query, void, undefined>
}

export declare class Reply {
  get replierId(): EntityGlobalId | null
  get result(): ReplyResult
}

export declare class ReplyError {
  get encoding(): Encoding
  get payload(): Bytes
}

export declare class ReplyHandler {
  recv(): Promise<Reply>
  tryRecv(): Reply | null
  stream(): ReplyStream
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class ReplyStream {
  [Symbol.asyncIterator](): AsyncGenerator<Reply, void, undefined>
}

export declare class RingChannel {
  constructor(capacity: number)
}

export declare class Sample {
  get payload(): Bytes
  get keyExpr(): KeyExpr
  get kind(): SampleKind
  get encoding(): Encoding
  get timestamp(): Timestamp | null
  get express(): boolean
  get priority(): Priority
  get congestionControl(): CongestionControl
  get reliability(): Reliability
  get attachment(): Bytes | null
  get sourceInfo(): SourceInfo | null
}

export declare class SampleMissListener {
  undeclare(): void
  recv(): Promise<Miss>
  tryRecv(): Miss | null
  stream(): MissStream
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class SampleStream {
  [Symbol.asyncIterator](): AsyncGenerator<Sample, void, undefined>
}

export declare class Scout {
  static scout(what: WhatAmIMatcher, config: Config, options?: ScoutOptions | undefined | null): Promise<Scout>
  stop(): void
  recv(): Promise<Hello>
  tryRecv(): Hello | null
  stream(): HelloStream
}

export declare class Selector {
  constructor(keyExpr: KeyExprArg, parameters?: string | undefined | null)
  get keyExpr(): KeyExpr
  get parameters(): Parameters
  split(): SelectorParts
}

export declare class Session {
  static open(config: Config): Promise<Session>
  get zid(): string
  get id(): EntityGlobalId
  get isClosed(): boolean
  newTimestamp(): Timestamp
  info(): SessionInfo
  config(): SessionConfig
  close(): Promise<void>
  put(keyExpr: KeyExprArg, payload: Payload, options?: PutOptions | undefined | null): Promise<void>
  get(selector: SelectorArg, options?: GetOptions | undefined | null): Promise<ReplyHandler>
  delete(keyExpr: KeyExprArg, options?: DeleteOptions | undefined | null): Promise<void>
  liveliness(): Liveliness
  declareKeyexpr(keyExpr: KeyExprArg): Promise<KeyExpr>
  declareQuerier(keyExpr: KeyExprArg, options?: QuerierOptions | undefined | null): Promise<Querier>
  declareQueryable(keyExpr: KeyExprArg, options?: QueryableOptions | undefined | null): Promise<Queryable>
  declareSubscriber(keyExpr: KeyExprArg, options?: SubscriberOptions | undefined | null): Promise<Subscriber>
  declarePublisher(keyExpr: KeyExprArg, options?: PublisherOptions | undefined | null): Promise<Publisher>
}

export declare class SessionConfig {
  get(key: string): string
  insertJson5(key: string, value: string): void
  toJson(): string
  queriesDefaultTimeoutMs(): bigint
  getPluginConfig(pluginName: string): string
}

export declare class SessionInfo {
  zid(): Promise<string>
  routersZid(): Promise<Array<string>>
  peersZid(): Promise<Array<string>>
  transports(): Promise<Array<Transport>>
  links(): Promise<Array<Link>>
  transportEventsListener(options?: TransportEventsListenerOptions | undefined | null): Promise<TransportEventsListener>
  linkEventsListener(options?: LinkEventsListenerOptions | undefined | null): Promise<LinkEventsListener>
}

export declare class SourceInfo {
  constructor(sourceId: EntityGlobalId, sourceSn: number)
  get sourceId(): EntityGlobalId
  get sourceSn(): number
}

export declare class Subscriber {
  get keyExpr(): KeyExpr
  get id(): EntityGlobalId
  sampleMissListener(options?: SampleMissListenerOptions | undefined | null): Promise<SampleMissListener>
  detectPublishers(options?: LivelinessSubscriberOptions | undefined | null): Promise<LivelinessSubscriber>
  undeclare(): void
  recv(): Promise<Sample>
  tryRecv(): Sample | null
  stream(): SampleStream
}

export declare class Timestamp {
  static parseRfc3339(s: string): Timestamp
  toStringRfc3339Lossy(): string
  getTime(): bigint
  getId(): string
  getDiffDuration(other: Timestamp): number
}

export declare class Transport {
  get zid(): string
  get whatami(): WhatAmI
  get isQos(): boolean
  get isMulticast(): boolean
}

export declare class TransportEvent {
  get kind(): SampleKind
  get transport(): Transport
}

export declare class TransportEventsListener {
  undeclare(): void
  recv(): Promise<TransportEvent>
  tryRecv(): TransportEvent | null
  stream(): TransportEventStream
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class TransportEventStream {
  [Symbol.asyncIterator](): AsyncGenerator<TransportEvent, void, undefined>
}

export declare class WhatAmIMatcher {
  static empty(): WhatAmIMatcher
  router(): WhatAmIMatcher
  peer(): WhatAmIMatcher
  client(): WhatAmIMatcher
  get isEmpty(): boolean
  matches(w: WhatAmI): boolean
  toStr(): string
}

export interface CacheConfig {
  maxSamples?: number
  repliesConfig?: RepliesConfig
}

export type CongestionControl =  'Drop'|
'Block'|
'BlockFirst';

export type ConsolidationMode =  'Auto'|
'None'|
'Monotonic'|
'Latest';

export interface DeleteOptions {
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  reliability?: Reliability
  allowedDestination?: Locality
  timestamp?: Timestamp
  attachment?: Payload
  sourceInfo?: SourceInfo
}

export interface EndPointParts {
  protocol: string
  address: string
  metadata: string
  config: string
}

export interface GetOptions {
  parameters?: Parameters
  target?: QueryTarget
  consolidation?: ConsolidationMode
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  allowedDestination?: Locality
  timeout?: number
  payload?: Payload
  encoding?: string
  attachment?: Payload
  sourceInfo?: SourceInfo
  cancellationToken?: CancellationToken
  channel?: FifoChannel | RingChannel
}

export interface HeartbeatConfig {
  periodMs: number
  sporadic?: boolean
}

export type HeartbeatMode =  'Heartbeat';

export interface HeartbeatRecovery {
  mode: HeartbeatMode
}

export interface HistoryConfig {
  detectLatePublishers?: boolean
  maxSamples?: number
  maxAgeSecs?: number
}

export type KeyExprArg =
  string | KeyExpr

export interface LinkEventsListenerOptions {
  history?: boolean
  transport?: Transport
  channel?: FifoChannel | RingChannel
}

export interface LinkPriorities {
  min: number
  max: number
}

export interface LivelinessGetOptions {
  timeout?: number
  cancellationToken?: CancellationToken
  channel?: FifoChannel | RingChannel
}

export interface LivelinessSubscriberOptions {
  history?: boolean
  channel?: FifoChannel | RingChannel
}

export type Locality =  'SessionLocal'|
'Remote'|
'Any';

export interface MatchingListenerOptions {
  channel?: FifoChannel | RingChannel
}

export interface MissDetectionConfig {
  heartbeat?: HeartbeatConfig
}

export type Payload =
  string | Uint8Array

export type PeriodicQueriesMode =  'PeriodicQueries';

export interface PeriodicQueriesRecovery {
  mode: PeriodicQueriesMode
  periodMs: number
}

export type Priority =  'RealTime'|
'InteractiveHigh'|
'InteractiveLow'|
'DataHigh'|
'Data'|
'DataLow'|
'Background';

export interface PublisherDeleteOptions {
  timestamp?: Timestamp
  attachment?: Payload
}

export interface PublisherOptions {
  encoding?: string
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  reliability?: Reliability
  allowedDestination?: Locality
  cache?: CacheConfig
  sampleMissDetection?: MissDetectionConfig
  publisherDetection?: boolean
  publisherDetectionMetadata?: string
}

export interface PublisherPutOptions {
  encoding?: string
  timestamp?: Timestamp
  attachment?: Payload
}

export interface PutOptions {
  encoding?: string
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  reliability?: Reliability
  allowedDestination?: Locality
  timestamp?: Timestamp
  attachment?: Payload
  sourceInfo?: SourceInfo
}

export interface QuerierGetOptions {
  parameters?: Parameters
  payload?: Payload
  encoding?: string
  attachment?: Payload
  sourceInfo?: SourceInfo
  cancellationToken?: CancellationToken
  channel?: FifoChannel | RingChannel
}

export interface QuerierOptions {
  target?: QueryTarget
  consolidation?: ConsolidationMode
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  allowedDestination?: Locality
  timeout?: number
  acceptReplies?: ReplyKeyExpr
}

export interface QueryableOptions {
  complete?: boolean
  allowedOrigin?: Locality
  channel?: FifoChannel | RingChannel
}

export type QueryTarget =  'BestMatching'|
'All'|
'AllComplete';

export type Reliability =  'BestEffort'|
'Reliable';

export interface RepliesConfig {
  priority?: Priority
  congestionControl?: CongestionControl
  express?: boolean
}

export interface ReplyDelOptions {
  express?: boolean
  timestamp?: Timestamp
  attachment?: Payload
  sourceInfo?: SourceInfo
}

export interface ReplyErrOptions {
  encoding?: string
}

export type ReplyKeyExpr =  'Any'|
'MatchingQuery';

export interface ReplyOptions {
  encoding?: string
  express?: boolean
  timestamp?: Timestamp
  attachment?: Payload
  sourceInfo?: SourceInfo
}

export type ReplyResult =
  ReplyResultSample | ReplyResultError

export interface ReplyResultError {
  sample: null
  error: ReplyError
}

export interface ReplyResultSample {
  sample: Sample
  error: null
}

export type SampleKind =  'Put'|
'Delete';

export interface SampleMissListenerOptions {
  channel?: FifoChannel | RingChannel
}

export interface ScoutOptions {
  channel?: FifoChannel | RingChannel
}

export type SelectorArg =
  string | KeyExpr | Selector

export interface SelectorParts {
  keyExpr: string
  parameters: string
}

export interface SubscriberOptions {
  allowedOrigin?: Locality
  history?: HistoryConfig
  recovery?: PeriodicQueriesRecovery | HeartbeatRecovery
  subscriberDetection?: boolean
  subscriberDetectionMetadata?: string
  queryTimeoutMs?: number
  channel?: FifoChannel | RingChannel
}

export interface TransportEventsListenerOptions {
  history?: boolean
  channel?: FifoChannel | RingChannel
}

export type WhatAmI =  'Router'|
'Peer'|
'Client';

export declare namespace zd {
  /**
   * An immutable schema value: build once with the `zd.*` builders, then call
   * `serialize`/`deserialize` as many times as needed. No lifecycle.
   */
  export class Schema {
    serialize(data: unknown): Bytes
    deserialize(bytes: Bytes): unknown
  }
  export function array(item: Schema): Schema
  export function bool(): Schema
  export function bytes(): Schema
  export function deserialize(schema: Schema, bytes: Bytes): unknown
  export function f32(): Schema
  export function f64(): Schema
  export function i16(): Schema
  export function i32(): Schema
  export function i64(): Schema
  export function i8(): Schema
  export function map(key: Schema, value: Schema): Schema
  export function object(fields: object): Schema
  export function serialize(schema: Schema, data: unknown): Bytes
  export function set(item: Schema): Schema
  export function string(): Schema
  export function tuple(items: Array<Schema>): Schema
  export function u16(): Schema
  export function u32(): Schema
  export function u64(): Schema
  export function u8(): Schema
}
