[package]
name = "dialtone"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/diskettejs/dialtone"
license = "MIT"
readme = "README.md"
keywords = ["NodeJS", "Node", "FFI", "NAPI", "n-api", "Zenoh"]

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.12.1", default-features = false, features = ["napi10", "async"] }
napi-derive = "3.6.3"

zenoh = { version = "1.9.0", features = ["unstable"] }
zenoh-ext = { version = "1.9.0", features = ["unstable"] }
zenoh-config = { version = "1.9.0" }

derive_more = { version = "2.1.1", default-features = false, features = ["from", "as_ref", "into"] }

[build-dependencies]
napi-build = "2.4.1"

[profile.release]
codegen-units = 1
lto = true
strip = "symbols"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
std_instead_of_core = { level = "warn", priority = -1 }
needless_pass_by_value = "allow"
multiple_crate_versions = "allow"
