/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Zenoh session configuration (defaults to peer mode).
 *
 * Controls how a session connects to the network — for example, explicit
 * `connect`/`listen` endpoints when multicast discovery isn't available between
 * processes. Build one with `Config.default()` or `Config.fromJson5()`, then pass
 * it to `Session.open()`.
 */
export declare class Config {
  /** Default configuration (peer mode). */
  static default(): Config
  /** Parse a JSON5 (or plain JSON, a subset of JSON5) configuration string. */
  static fromJson5(json5: string): Config
  /** Load configuration from a file path (JSON5/JSON/YAML per extension). */
  static fromFile(path: string): Config
  /** Load configuration from the file referenced by the `ZENOH_CONFIG` env var. */
  static fromEnv(): Config
  /**
   * Insert or override a value at a key path; `value` is a JSON5 fragment.
   * e.g. `insertJson5("scouting/multicast/enabled", "false")`.
   */
  insertJson5(key: string, value: string): void
  /** Serialize the configuration to a JSON string (private fields elided). */
  toString(): string
}

/**
 * A publisher declared on a session. Sends values on a fixed key expression with
 * the QoS chosen when it was declared. Call `undeclare()` when you're done.
 */
export declare class Publisher {
  /** The key expression this publisher sends on. */
  get keyExpr(): string
  /** Publish a value on the publisher's key expression. */
  put(payload: string | Uint8Array, options?: PublisherPutOptions | undefined | null): Promise<void>
  /** Publish a delete (tombstone) on the publisher's key expression. */
  delete(options?: PublisherDeleteOptions | undefined | null): Promise<void>
  /** Undeclare the publisher and release its resources. */
  undeclare(): Promise<void>
}

export declare class Session {
  /**
   * Open a Zenoh session (default = peer mode).
   *
   * `config` accepts a JSON5 string (a subset; plain JSON works too), a `Config`
   * instance, or nothing (default peer config). The string form is a convenience
   * over `Config.fromJson5`.
   */
  static open(config?: string | Config | undefined | null): Promise<Session>
  /** Zenoh ID of this session. */
  get zid(): string
  /** This session's view of the network (its zid plus connected routers/peers). */
  info(): Promise<SessionInfo>
  /** Publish a value directly on the session, without declaring a publisher. */
  put(keyExpr: string, payload: string | Uint8Array, options?: PutOptions | undefined | null): Promise<void>
  /** Publish a delete (tombstone) directly on the session. */
  delete(keyExpr: string, options?: DeleteOptions | undefined | null): Promise<void>
  /**
   * Declare a publisher. QoS / addressing is fixed here; per-message overrides go
   * on `publisher.put()`.
   */
  declarePublisher(keyExpr: string, options?: PublisherOptions | undefined | null): Promise<Publisher>
  /**
   * Declare a subscriber. The returned object is async-iterable:
   * `for await (const sample of sub) { ... }`.
   */
  declareSubscriber(keyExpr: string): Promise<Subscriber>
  /** Close the session and release its resources. */
  close(): Promise<void>
}

/**
 * A subscriber declared on a session. It is async-iterable — consume samples with
 * `for await (const sample of sub) { ... }` — or pull them one at a time with
 * `receive()`.
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class Subscriber {
  /** The key expression this subscriber listens on. */
  get keyExpr(): string
  /** Pull one sample, or `null` once the subscription is closed/undeclared. */
  receive(): Promise<Sample | null>
  /** Undeclare the subscription and release its resources. */
  undeclare(): Promise<void>
  [Symbol.asyncIterator](): AsyncGenerator<Sample, void, undefined>
}

/** How a message behaves when the network is congested. */
export type CongestionControl = /** Drop the message rather than wait. */
'Drop'|
/** Block until the message can be sent. */
'Block';

/**
 * QoS and metadata overrides for a session-level `delete`, applied to this call
 * only. A `delete` carries no payload, so there is no `encoding` option.
 */
export interface DeleteOptions {
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  attachment?: string | Uint8Array
  allowedDestination?: Locality
}

/**
 * Restricts which subscribers a message can reach, by their location relative to
 * this session.
 */
export type Locality = /** Only subscribers within this same session. */
'SessionLocal'|
/** Only subscribers in other sessions. */
'Remote'|
/** Any subscriber whether local or remote. */
'Any';

/** Transmission priority, from highest (`RealTime`) to lowest (`Background`). */
export type Priority =  'RealTime'|
'InteractiveHigh'|
'InteractiveLow'|
'DataHigh'|
'Data'|
'DataLow'|
'Background';

/** Per-message options for `publisher.delete()`. */
export interface PublisherDeleteOptions {
  attachment?: string | Uint8Array
}

/** QoS and addressing for a publisher, fixed when it is declared. */
export interface PublisherOptions {
  encoding?: string
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  allowedDestination?: Locality
}

/**
 * Per-message options for `publisher.put()`. A publisher's QoS is fixed when it is
 * declared, so only the payload encoding and attachment can vary per message.
 */
export interface PublisherPutOptions {
  encoding?: string
  attachment?: string | Uint8Array
}

/**
 * QoS and metadata overrides for a session-level `put`, applied to this call
 * only. A declared publisher fixes its QoS up front; a session `put` lets you
 * set it per message.
 */
export interface PutOptions {
  encoding?: string
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  attachment?: string | Uint8Array
  allowedDestination?: Locality
}

/**
 * A value delivered to a subscriber, with its key expression, payload, and the
 * QoS and metadata it was published with.
 */
export interface Sample {
  keyExpr: string
  payload: Uint8Array
  kind: SampleKind
  encoding: string
  timestamp?: Timestamp
  congestionControl: CongestionControl
  priority: Priority
  express: boolean
  attachment?: Uint8Array
}

/** Whether a sample carries a published value or marks a deletion. */
export type SampleKind = /** A value was published. */
'Put'|
/** A value was deleted (tombstone). */
'Delete';

/** Snapshot of the session's view of the network, from `session.info()`. */
export interface SessionInfo {
  /** Zenoh ID of this session. */
  zid: string
  /** Zenoh IDs of the routers this session is connected to. */
  routers: Array<string>
  /** Zenoh IDs of the peers this session is connected to. */
  peers: Array<string>
}

/**
 * The timestamp attached to a sample. Use the `ntp64ToDate(ntp64)` helper to turn
 * the raw NTP64 value into a JS `Date`.
 */
export interface Timestamp {
  /** Zenoh ID of the source that created the timestamp. */
  id: string
  /** Raw NTP64 timestamp value. */
  ntp64: bigint
}
