/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Zenoh session configuration (mirrors `zenoh::Config`).
 *
 * The configuration tree is opaque; construct it with one of the factory
 * methods. There is intentionally no public constructor.
 */
export declare class Config {
  /** The default configuration (peer mode, default endpoints). */
  static default(): Config
  /** Load configuration from a JSON5 string. */
  static fromJson5(json5: string): Config
  /** Load configuration from a JSON5 file at `path`. */
  static fromFile(path: string): Config
  /**
   * Load configuration from the file pointed to by the `ZENOH_CONFIG`
   * environment variable.
   */
  static fromEnv(): Config
}

/**
 * A publisher bound to a key expression, with QoS fixed at declaration time.
 * Create one with [`Session::declarePublisher`].
 */
export declare class Publisher {
  /** Publish a `Put` sample to this publisher's key expression. */
  put(payload: string | Uint8Array, options?: PublisherPutOptions | undefined | null): Promise<void>
  /** Publish a `Delete` sample to this publisher's key expression. */
  delete(options?: PublisherDeleteOptions | undefined | null): Promise<void>
  /** Whether any subscribers currently match this publisher's key expression. */
  matchingStatus(): Promise<MatchingStatus>
  /**
   * Undeclare this publisher. Subsequent operations on it will error.
   *
   * Resolves synchronously, so awaiting the returned value is optional.
   */
  undeclare(): void
  /** The key expression this publisher publishes to. */
  get keyExpr(): string
  /** The default encoding applied to publications. */
  get encoding(): string
  /** The congestion control strategy. */
  get congestionControl(): CongestionControl
  /** The publication priority. */
  get priority(): Priority
  /** The delivery reliability. */
  get reliability(): Reliability
  /** This publisher's globally-unique entity id. */
  get id(): EntityGlobalId
}

/**
 * An open connection to the Zenoh network — the entry point from which every
 * publisher, subscriber, and query is declared.
 *
 * `zenoh::Session` is internally an `Arc`, so the underlying session lives as
 * long as any handle to it. It is closed either explicitly via [`close`] or
 * when this handle is garbage-collected (the Rust `Drop` closes the last
 * remaining reference).
 *
 * [`close`]: Session::close
 */
export declare class Session {
  /**
   * Open a session with the given configuration, or the default configuration
   * when omitted.
   */
  static open(config?: Config | undefined | null): Promise<Session>
  /** Close the session, undeclaring every entity declared on it. */
  close(): Promise<void>
  /**
   * Publish a `Put` sample: send `payload` to every subscriber whose key
   * expression matches `key_expr`.
   */
  put(keyExpr: string, payload: string | Uint8Array, options?: PutOptions | undefined | null): Promise<void>
  /**
   * Publish a `Delete` sample for `key_expr`, signalling that the value at that
   * key is no longer valid.
   */
  delete(keyExpr: string, options?: DeleteOptions | undefined | null): Promise<void>
  /**
   * Declare a [`Publisher`] for `key_expr`. Its QoS is fixed at declaration
   * time; per-publication `put`/`delete` can override only payload fields.
   */
  declarePublisher(keyExpr: string, options?: PublisherOptions | undefined | null): Promise<Publisher>
  /** Create a new timestamp using this session's hybrid logical clock. */
  newTimestamp(): Timestamp
  /** Access information about this session and the nodes it is connected to. */
  info(): SessionInfo
  /** The Zenoh ID of this session, as a hex string. */
  get zid(): string
  /** Whether the session has been closed. */
  get isClosed(): boolean
}

/** Information about a [`Session`] and the routers/peers it is connected to. */
export declare class SessionInfo {
  /** The Zenoh ID of this session. */
  zid(): Promise<string>
  /** The Zenoh IDs of the routers this session is currently connected to. */
  routersZid(): Promise<Array<string>>
  /** The Zenoh IDs of the peers this session is currently connected to. */
  peersZid(): Promise<Array<string>>
}

/** What a node does when a message reaches it with a full transmission queue. */
export type CongestionControl = /** Drop the message (the default for `put`/`delete`). */
'Drop'|
/** Block the caller until the queue has room. */
'Block'|
/**
 * When transmitting a message in a node with a full queue| the node will wait for queue to progress|
 * but only for the first message sent with this strategy; other messages will be dropped.
 */
'BlockFirst';

/** Options for [`Session::delete`]. */
export interface DeleteOptions {
  /** Optional attachment carried alongside the deletion. */
  attachment?: string | Uint8Array
  /** Congestion control strategy (default: `Drop`). */
  congestionControl?: CongestionControl
  /** Priority of the deletion (default: `Data`). */
  priority?: Priority
  /** When `true`, the message is sent unbatched, trading throughput for latency. */
  express?: boolean
  /** Delivery reliability (default: `Reliable`). */
  reliability?: Reliability
  /** Restrict which matching subscribers receive the deletion (default: `Any`). */
  allowedDestination?: Locality
  /** Timestamp to attach; obtain one from [`Session::newTimestamp`]. */
  timestamp?: Timestamp
  /** Source metadata (producing entity + sequence number). */
  sourceInfo?: SourceInfo
}

/**
 * Globally-unique identifier of a Zenoh entity (a session, publisher, …): the
 * owning session's Zenoh ID together with a session-local entity id.
 */
export interface EntityGlobalId {
  /** Zenoh ID of the owning session, as a hex string. */
  zid: string
  /** Session-local entity id. */
  eid: number
}

/**
 * Restricts which entities a publication reaches (or a subscription accepts),
 * by whether they live in the same session or elsewhere.
 */
export type Locality = /** Only entities in the same session. */
'SessionLocal'|
/** Only remote entities (not in the same session). */
'Remote'|
/** Both local and remote entities (the default). */
'Any';

/**
 * Whether a publisher currently has matching subscribers (or, later, a querier
 * has matching queryables).
 */
export interface MatchingStatus {
  /** `true` if at least one matching entity currently exists. */
  matching: boolean
}

/** Priority of a publication. Listed highest to lowest; `Data` is the default. */
export type Priority =  'RealTime'|
'InteractiveHigh'|
'InteractiveLow'|
'DataHigh'|
'Data'|
'DataLow'|
'Background';

/** Options for [`Publisher::delete`]. */
export interface PublisherDeleteOptions {
  /** Optional attachment carried alongside the deletion. */
  attachment?: string | Uint8Array
  /** Timestamp to attach; obtain one from [`Session::newTimestamp`]. */
  timestamp?: Timestamp
  /** Source metadata (producing entity + sequence number). */
  sourceInfo?: SourceInfo
}

/**
 * Options for [`Session::declarePublisher`]. These settings are fixed for the
 * publisher's lifetime; per-publication `put`/`delete` may only override
 * payload-level fields (encoding, attachment, …), not QoS.
 */
export interface PublisherOptions {
  /** Default encoding for publications. */
  encoding?: string
  /** Congestion control strategy (default: `Drop`). */
  congestionControl?: CongestionControl
  /** Priority of publications (default: `Data`). */
  priority?: Priority
  /** When `true`, messages are sent unbatched, trading throughput for latency. */
  express?: boolean
  /** Delivery reliability (default: `Reliable`). */
  reliability?: Reliability
  /** Restrict which matching subscribers receive the data (default: `Any`). */
  allowedDestination?: Locality
}

/** Options for [`Publisher::put`]. */
export interface PublisherPutOptions {
  /** Encoding of this payload, overriding the publisher's default. */
  encoding?: string
  /** Optional attachment carried alongside the payload. */
  attachment?: string | Uint8Array
  /** Timestamp to attach; obtain one from [`Session::newTimestamp`]. */
  timestamp?: Timestamp
  /** Source metadata (producing entity + sequence number). */
  sourceInfo?: SourceInfo
}

/** Options for [`Session::put`]. */
export interface PutOptions {
  /** Encoding of the payload (e.g. `"text/plain"`, `"application/json"`). */
  encoding?: string
  /** Optional attachment carried alongside the payload. */
  attachment?: string | Uint8Array
  /** Congestion control strategy (default: `Drop`). */
  congestionControl?: CongestionControl
  /** Priority of the publication (default: `Data`). */
  priority?: Priority
  /** When `true`, the message is sent unbatched, trading throughput for latency. */
  express?: boolean
  /** Delivery reliability (default: `Reliable`). */
  reliability?: Reliability
  /** Restrict which matching subscribers receive the data (default: `Any`). */
  allowedDestination?: Locality
  /** Timestamp to attach; obtain one from [`Session::newTimestamp`]. */
  timestamp?: Timestamp
  /** Source metadata (producing entity + sequence number). */
  sourceInfo?: SourceInfo
}

/**
 * Reliability of message delivery.
 *
 * **NOTE**: as in Zenoh itself, reliability does not currently trigger wire
 * retransmission; it is a marker that may influence link selection.
 */
export type Reliability = /** Messages may be lost. */
'BestEffort'|
/** Messages are guaranteed to be delivered (the default). */
'Reliable';

/**
 * Source metadata for a publication: which entity produced the sample and the
 * source's own sequence number for it. Used by advanced pub/sub (e.g. for
 * missing-sample detection); the base primitives just transmit it.
 */
export interface SourceInfo {
  /** Id of the entity that produced the sample. */
  sourceId: EntityGlobalId
  /** The source's sequence number for this sample. */
  sourceSn: number
}

/**
 * A Zenoh timestamp: a hybrid-logical-clock time plus the id of the clock that
 * produced it. Obtain one from [`Session::newTimestamp`]; it can then be
 * passed back via the `timestamp` publication option.
 */
export interface Timestamp {
  /** The NTP64-encoded time component (a 64-bit value). */
  time: bigint
  /** The id of the source clock, as a hex string (a Zenoh ID). */
  id: string
}
