/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Zenoh session configuration (mirrors `zenoh::Config`).
 *
 * The configuration tree is opaque; construct it with one of the factory
 * methods. There is intentionally no public constructor.
 */
export declare class Config {
  /** The default configuration (peer mode, default endpoints). */
  static default(): Config
  /** Load configuration from a JSON5 string. */
  static fromJson5(json5: string): Config
  /** Load configuration from a JSON5 file at `path`. */
  static fromFile(path: string): Config
  /**
   * Load configuration from the file pointed to by the `ZENOH_CONFIG`
   * environment variable.
   */
  static fromEnv(): Config
}

/**
 * Notifies of changes to a publisher's [`MatchingStatus`], delivered through a
 * channel. Obtain one from [`Publisher::matchingListener`].
 *
 * Consume it with `for await (const status of listener)`, or pull with
 * `recv()` / `tryRecv()`. The listener is tied to its publisher: if the
 * publisher is undeclared or dropped, iteration ends.
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class MatchingListener {
  /**
   * Wait for the next matching-status change, resolving to `null` once the
   * listener is closed.
   */
  recv(): Promise<MatchingStatus | null>
  /**
   * Return a buffered status if one is immediately available, or `null` if the
   * channel is currently empty. Throws once the listener has disconnected,
   * letting a polling loop tell "nothing yet" apart from "closed".
   */
  tryRecv(): MatchingStatus | null
  /**
   * Undeclare the listener; any buffered statuses are dropped with the handler.
   * Resolves synchronously.
   */
  undeclare(): void
  [Symbol.asyncIterator](): AsyncGenerator<MatchingStatus, void, undefined>
}

/**
 * A publisher bound to a key expression, with QoS fixed at declaration time.
 * Create one with [`Session::declarePublisher`].
 */
export declare class Publisher {
  /** Publish a `Put` sample to this publisher's key expression. */
  put(payload: string | Uint8Array, options?: PublisherPutOptions | undefined | null): Promise<void>
  /** Publish a `Delete` sample to this publisher's key expression. */
  delete(options?: PublisherDeleteOptions | undefined | null): Promise<void>
  /** Whether any subscribers currently match this publisher's key expression. */
  matchingStatus(): Promise<MatchingStatus>
  /**
   * Declare a [`MatchingListener`] that notifies when this publisher's set of
   * matching subscribers changes. The optional channel `handler` (FIFO or
   * Ring) backs the notifications; defaults to FIFO.
   */
  matchingListener(handler?: ChannelHandler | undefined | null): Promise<MatchingListener>
  /**
   * Undeclare this publisher. Subsequent operations on it will error.
   *
   * Resolves synchronously, so awaiting the returned value is optional.
   */
  undeclare(): void
  /** The key expression this publisher publishes to. */
  get keyExpr(): string
  /** The default encoding applied to publications. */
  get encoding(): string
  /** The congestion control strategy. */
  get congestionControl(): CongestionControl
  /** The publication priority. */
  get priority(): Priority
  /** The delivery reliability. */
  get reliability(): Reliability
  /** This publisher's globally-unique entity id. */
  get id(): EntityGlobalId
}

/**
 * A data sample received by a subscriber (or a query reply): the payload plus
 * all of its metadata.
 *
 * Fields are exposed as lazy getters; the payload is only copied into a
 * `Buffer` when accessed.
 */
export declare class Sample {
  /** The key expression this sample was published on. */
  get keyExpr(): string
  /** The payload bytes. */
  get payload(): Buffer
  /** Whether this sample is a `Put` or a `Delete`. */
  get kind(): SampleKind
  /** The payload encoding. */
  get encoding(): string
  /** The timestamp attached to the sample, if any. */
  get timestamp(): Timestamp | null
  /** The congestion control strategy the sample was sent with. */
  get congestionControl(): CongestionControl
  /** The priority the sample was sent with. */
  get priority(): Priority
  /** Whether the sample was sent express (unbatched). */
  get express(): boolean
  /** The delivery reliability the sample was sent with. */
  get reliability(): Reliability
  /** The attachment bytes, if any. */
  get attachment(): Buffer | null
  /** The source metadata, if any. */
  get sourceInfo(): SourceInfo | null
}

/**
 * An open connection to the Zenoh network — the entry point from which every
 * publisher, subscriber, and query is declared. Close it with `close`.
 */
export declare class Session {
  /**
   * Open a session with the given configuration, or the default configuration
   * when omitted.
   */
  static open(config?: Config | undefined | null): Promise<Session>
  /** Close the session, undeclaring every entity declared on it. */
  close(): Promise<void>
  /**
   * Publish a `Put` sample: send `payload` to every subscriber whose key
   * expression matches `key_expr`.
   */
  put(keyExpr: string, payload: string | Uint8Array, options?: PutOptions | undefined | null): Promise<void>
  /**
   * Publish a `Delete` sample for `key_expr`, signalling that the value at that
   * key is no longer valid.
   */
  delete(keyExpr: string, options?: DeleteOptions | undefined | null): Promise<void>
  /**
   * Declare a [`Publisher`] for `key_expr`. Its QoS is fixed at declaration
   * time; per-publication `put`/`delete` can override only payload fields.
   */
  declarePublisher(keyExpr: string, options?: PublisherOptions | undefined | null): Promise<Publisher>
  /**
   * Declare a [`Subscriber`] for `key_expr`. Samples are delivered through a
   * FIFO channel, consumable as an async iterator or via `recv`/`tryRecv`.
   */
  declareSubscriber(keyExpr: string, options?: SubscriberOptions | undefined | null): Promise<Subscriber>
  /** Create a new timestamp using this session's hybrid logical clock. */
  newTimestamp(): Timestamp
  /** Access information about this session and the nodes it is connected to. */
  info(): SessionInfo
  /** The Zenoh ID of this session, as a hex string. */
  get zid(): string
  /** Whether the session has been closed. */
  get isClosed(): boolean
}

/** Information about a [`Session`] and the routers/peers it is connected to. */
export declare class SessionInfo {
  /** The Zenoh ID of this session. */
  zid(): Promise<string>
  /** The Zenoh IDs of the routers this session is currently connected to. */
  routersZid(): Promise<Array<string>>
  /** The Zenoh IDs of the peers this session is currently connected to. */
  peersZid(): Promise<Array<string>>
}

/**
 * A subscriber that delivers [`Sample`]s through a channel.
 *
 * Consume it with `for await (const sample of subscriber)`, or pull samples
 * individually with `recv()` / `tryRecv()`. Iteration ends (yields `null`)
 * once the subscriber is undeclared — its buffered samples are dropped with the
 * handler, as in zenoh — or once the session/link closes and any buffered
 * samples have been drained.
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class Subscriber {
  /**
   * Wait for the next sample, resolving to `null` once the subscriber is
   * undeclared, or once it closes and all buffered samples have been drained.
   */
  recv(): Promise<Sample | null>
  /**
   * Return a buffered sample if one is immediately available, or `null` if the
   * channel is currently empty. Throws once the subscriber has disconnected
   * (undeclared, or the session closed and all buffered samples drained),
   * letting a polling loop tell "nothing yet" apart from "closed".
   */
  tryRecv(): Sample | null
  /**
   * Undeclare the subscriber. Iteration / `recv` then end and `tryRecv` throws;
   * any buffered samples are dropped with the handler. Resolves synchronously.
   */
  undeclare(): void
  /** The key expression this subscriber is subscribed to. */
  get keyExpr(): string
  /** This subscriber's globally-unique entity id. */
  get id(): EntityGlobalId
  [Symbol.asyncIterator](): AsyncGenerator<Sample, void, undefined>
}

/** Channel handler configuration for a subscriber or listener. */
export interface ChannelHandler {
  /** `Fifo` or `Ring`. */
  kind: ChannelType
  /** Channel capacity. Defaults to Zenoh's default channel size when omitted. */
  capacity?: number
}

/** Which channel kind buffers items for a subscriber or listener. */
export type ChannelType = /** Bounded FIFO queue; applies backpressure to Zenoh when full. */
'Fifo'|
/** Bounded ring buffer; drops the oldest item when full (never blocks). */
'Ring';

/** What a node does when a message reaches it with a full transmission queue. */
export type CongestionControl = /** Drop the message (the default for `put`/`delete`). */
'Drop'|
/** Block the caller until the queue has room. */
'Block'|
/**
 * When transmitting a message in a node with a full queue| the node will wait for queue to progress|
 * but only for the first message sent with this strategy; other messages will be dropped.
 */
'BlockFirst';

/** Options for [`Session::delete`]. */
export interface DeleteOptions {
  /** Optional attachment carried alongside the deletion. */
  attachment?: string | Uint8Array
  /** Congestion control strategy (default: `Drop`). */
  congestionControl?: CongestionControl
  /** Priority of the deletion (default: `Data`). */
  priority?: Priority
  /** When `true`, the message is sent unbatched, trading throughput for latency. */
  express?: boolean
  /** Delivery reliability (default: `Reliable`). */
  reliability?: Reliability
  /** Restrict which matching subscribers receive the deletion (default: `Any`). */
  allowedDestination?: Locality
  /** Timestamp to attach; obtain one from [`Session::newTimestamp`]. */
  timestamp?: Timestamp
  /** Source metadata (producing entity + sequence number). */
  sourceInfo?: SourceInfo
}

/**
 * Globally-unique identifier of a Zenoh entity (a session, publisher, …): the
 * owning session's Zenoh ID together with a session-local entity id.
 */
export interface EntityGlobalId {
  /** Zenoh ID of the owning session, as a hex string. */
  zid: string
  /** Session-local entity id. */
  eid: number
}

/**
 * Restricts which entities a publication reaches (or a subscription accepts),
 * by whether they live in the same session or elsewhere.
 */
export type Locality = /** Only entities in the same session. */
'SessionLocal'|
/** Only remote entities (not in the same session). */
'Remote'|
/** Both local and remote entities (the default). */
'Any';

/**
 * Whether a publisher currently has matching subscribers (or, later, a querier
 * has matching queryables).
 */
export interface MatchingStatus {
  /** `true` if at least one matching entity currently exists. */
  matching: boolean
}

/** Priority of a publication. Listed highest to lowest; `Data` is the default. */
export type Priority =  'RealTime'|
'InteractiveHigh'|
'InteractiveLow'|
'DataHigh'|
'Data'|
'DataLow'|
'Background';

/** Options for [`Publisher::delete`]. */
export interface PublisherDeleteOptions {
  /** Optional attachment carried alongside the deletion. */
  attachment?: string | Uint8Array
  /** Timestamp to attach; obtain one from [`Session::newTimestamp`]. */
  timestamp?: Timestamp
  /** Source metadata (producing entity + sequence number). */
  sourceInfo?: SourceInfo
}

/**
 * Options for [`Session::declarePublisher`]. These settings are fixed for the
 * publisher's lifetime; per-publication `put`/`delete` may only override
 * payload-level fields (encoding, attachment, …), not QoS.
 */
export interface PublisherOptions {
  /** Default encoding for publications. */
  encoding?: string
  /** Congestion control strategy (default: `Drop`). */
  congestionControl?: CongestionControl
  /** Priority of publications (default: `Data`). */
  priority?: Priority
  /** When `true`, messages are sent unbatched, trading throughput for latency. */
  express?: boolean
  /** Delivery reliability (default: `Reliable`). */
  reliability?: Reliability
  /** Restrict which matching subscribers receive the data (default: `Any`). */
  allowedDestination?: Locality
}

/** Options for [`Publisher::put`]. */
export interface PublisherPutOptions {
  /** Encoding of this payload, overriding the publisher's default. */
  encoding?: string
  /** Optional attachment carried alongside the payload. */
  attachment?: string | Uint8Array
  /** Timestamp to attach; obtain one from [`Session::newTimestamp`]. */
  timestamp?: Timestamp
  /** Source metadata (producing entity + sequence number). */
  sourceInfo?: SourceInfo
}

/** Options for [`Session::put`]. */
export interface PutOptions {
  /** Encoding of the payload (e.g. `"text/plain"`, `"application/json"`). */
  encoding?: string
  /** Optional attachment carried alongside the payload. */
  attachment?: string | Uint8Array
  /** Congestion control strategy (default: `Drop`). */
  congestionControl?: CongestionControl
  /** Priority of the publication (default: `Data`). */
  priority?: Priority
  /** When `true`, the message is sent unbatched, trading throughput for latency. */
  express?: boolean
  /** Delivery reliability (default: `Reliable`). */
  reliability?: Reliability
  /** Restrict which matching subscribers receive the data (default: `Any`). */
  allowedDestination?: Locality
  /** Timestamp to attach; obtain one from [`Session::newTimestamp`]. */
  timestamp?: Timestamp
  /** Source metadata (producing entity + sequence number). */
  sourceInfo?: SourceInfo
}

/**
 * Reliability of message delivery.
 *
 * **NOTE**: as in Zenoh itself, reliability does not currently trigger wire
 * retransmission; it is a marker that may influence link selection.
 */
export type Reliability = /** Messages may be lost. */
'BestEffort'|
/** Messages are guaranteed to be delivered (the default). */
'Reliable';

/** Whether a sample was produced by a `put` or a `delete`. */
export type SampleKind = /** Issued by a `put`. */
'Put'|
/** Issued by a `delete`. */
'Delete';

/**
 * Source metadata for a publication: which entity produced the sample and the
 * source's own sequence number for it. Used by advanced pub/sub (e.g. for
 * missing-sample detection); the base primitives just transmit it.
 */
export interface SourceInfo {
  /** Id of the entity that produced the sample. */
  sourceId: EntityGlobalId
  /** The source's sequence number for this sample. */
  sourceSn: number
}

/** Options for [`Session::declareSubscriber`]. */
export interface SubscriberOptions {
  /** Restrict which publishers' samples are accepted (default: `Any`). */
  allowedOrigin?: Locality
  /** Channel handler (FIFO or Ring) backing delivery. Defaults to FIFO. */
  handler?: ChannelHandler
}

/**
 * A Zenoh timestamp: a hybrid-logical-clock time plus the id of the clock that
 * produced it. Obtain one from [`Session::newTimestamp`]; it can then be
 * passed back via the `timestamp` publication option.
 */
export interface Timestamp {
  /** The NTP64-encoded time component (a 64-bit value). */
  time: bigint
  /** The id of the source clock, as a hex string (a Zenoh ID). */
  id: string
}
