import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vitepress'
import { transformerTwoslash } from '@shikijs/vitepress-twoslash'

// Repo root, resolved from this config file (docs/.vitepress/config.ts).
const root = fileURLToPath(new URL('../../', import.meta.url))

// The API sidebar is generated by `typedoc-vitepress-theme` into docs/api.
// `docs:dev` / `docs:build` run `docs:api` first, so it exists; fall back to
// an empty list so a stray `vitepress dev` before generation doesn't crash.
function apiSidebar() {
  try {
    return JSON.parse(readFileSync(new URL('../api/typedoc-sidebar.json', import.meta.url), 'utf8'))
  } catch {
    return []
  }
}

export default defineConfig({
  title: 'Dialtone',
  description: 'Node.js native bindings for Zenoh',
  // GitHub project-pages path (https://diskettejs.github.io/dialtone/).
  // Change to '/' for a custom domain or user/org root.
  base: '/dialtone/',
  cleanUrls: true,
  // TypeDoc-generated markdown can emit links VitePress flags as dead; relax
  // during the initial rollout and tighten once the API pages settle.
  ignoreDeadLinks: true,

  markdown: {
    codeTransformers: [
      // Type-checks fenced blocks tagged ```ts twoslash against the real
      // index.d.ts and renders hover types. Flip to check EVERY ts block by
      // setting `explicitTrigger: false` (see README / docs contributing notes).
      transformerTwoslash({
        twoslashOptions: {
          // Twoslash already defaults to module/target ESNext with the right
          // libs; we only add what's needed to resolve the package import.
          compilerOptions: {
            baseUrl: root,
            paths: { '@diskette/dialtone': ['./index.d.ts'] },
            moduleResolution: 100, // Bundler — supports `paths`
            types: ['node'], // console, node:timers/promises, etc.
          },
        },
      }),
    ],
  },

  themeConfig: {
    nav: [
      { text: 'Guide', link: '/quick-start' },
      { text: 'API', link: '/api/' },
    ],
    search: { provider: 'local' },
    sidebar: {
      '/api/': [{ text: 'API Reference', items: apiSidebar() }],
      '/': [
        {
          text: 'Guides',
          items: [
            { text: 'Quick Start', link: '/quick-start' },
            { text: 'Key Expressions', link: '/key-expressions' },
            { text: 'Publish & Subscribe', link: '/pub-sub' },
            { text: 'Querying', link: '/querying' },
            { text: 'Serialization & Payloads', link: '/serialization' },
            { text: 'Configuration & Sessions', link: '/configuration' },
            { text: 'Lifecycle & Cleanup', link: '/lifecycle' },
          ],
        },
        { text: 'Reference', items: [{ text: 'API', link: '/api/' }] },
      ],
    },
    socialLinks: [{ icon: 'github', link: 'https://github.com/diskettejs/dialtone' }],
    editLink: {
      pattern: 'https://github.com/diskettejs/dialtone/edit/main/docs/:path',
    },
  },
})
